Repository RAF-SI-2021/banka-front, pull requests merged in 2022-06, with the labels that each got.

#179 Cypress
  .github/workflows/tests.yml
  cypress/integration/capital.spec.js
  cypress/integration/login.spec.js
  cypress/integration/stocks.spec.js
  cypress/integration/trade.spec.js
  cypress/integration/transactions.spec.js
  cypress/integration/users.spec.js
  cypress/support/index.js
  package-lock.json
  src/components/common/Block.jsx
Labels: in progress

#188 Add .prow.yaml
  .prow.yaml
Labels: lgtm, approved

#189 Test
  .prow.yaml
Labels: dco-signoff: yes, size/XS, do-not-merge/hold

#190 Add .prow.yaml and OWNERS
  .prow.yaml
  OWNERS
Labels: dco-signoff: yes, size/S

#192 Env
  .env
  .env.development.example
  .gitignore
  .prow.yaml
  OWNERS
  README.md
  src/clients/accountClient.js
  src/clients/capital.js
  src/clients/client.js
  src/clients/stocks.js
Labels: size/L

#193 Agent ne moze da vidi odobri/odbij dugmice kod narudzbina koji se cekaju
  package-lock.json
  src/pages/dashboard/transactionappr.jsx
Labels: approved, size/XXL

#194 Isp 1
  src/pages/dashboard/list.jsx
Labels: approved, size/XS
