Repository RAF-SI-2021/banka-front, pull requests merged in 2022-07, with the labels that each got.

#195 Dodati testovi
  cypress/integration/information.spec.js
  cypress/integration/login.spec.js
  cypress/integration/users.spec.js
Labels: size/XL

#196 Sitnice
  cypress/integration/capital.spec.js
  cypress/integration/information.spec.js
  cypress/integration/login.spec.js
  src/clients/accountClient.js
Labels: approved, size/S

#199 OTC implementacija
  cypress/integration/capital.spec.js
  package-lock.json
  package.json
  src/CreateAgreementModal.jsx
  src/clients/accountClient.js
  src/clients/agreementClient.js
  src/clients/api.js
  src/clients/client.js
  src/clients/companyClient.js
  src/clients/marginClient.js
  src/clients/stocks.js
  src/components/AgreementsTable.jsx
  src/components/CompanyDropdown.jsx
  src/components/CurrencyDropdown.jsx
  src/components/FinalizeAgreementModal.jsx
  src/components/FutureDropdown.jsx
  src/components/Header.jsx
  src/components/Payment.jsx
  src/components/StocksDropdown.jsx
  src/components/common/Autocomplete.jsx
  src/components/common/Autocomplete.stories.jsx
  src/components/common/Button.jsx
  src/components/common/Form.jsx
  src/components/common/Modal.jsx
  src/components/common/Select.jsx
  src/components/common/Table.jsx
  src/components/common/TextArea.jsx
  src/components/common/TextField.jsx
  src/components/company/AgreementPointModal.jsx
  src/components/company/CompanyAgreements.jsx
  src/components/company/CompanyBankAccounts.jsx
  src/components/company/CompanyContact.jsx
  src/components/company/CompanyInformation.jsx
  src/components/company/CreateCompanyModal.jsx
  src/components/margins/MarginAddTransactionModal.jsx
  src/components/margins/MarginKapitalBlock.jsx
  src/components/margins/MarginKapitalModal.jsx
  src/components/margins/MarginStateBlock.jsx
  src/components/margins/MarginTransactionModal.jsx
  src/pages/dashboard/agreement-list.jsx
  src/pages/dashboard/agreement-single.jsx
  src/pages/dashboard/capital.jsx
  src/pages/dashboard/company-list.jsx
  src/pages/dashboard/company-single.jsx
  src/pages/dashboard/trade.jsx
  src/routes.jsx
Labels: approved, size/XXL

#200 Mergovanje grane ispit-1 sa masterom
  .env
  .env.development.example
  .gitignore
  README.md
  cypress/integration/capital.spec.js
  cypress/integration/information.spec.js
  cypress/integration/login.spec.js
  cypress/integration/users.spec.js
  package-lock.json
  package.json
  src/CreateAgreementModal.jsx
  src/clients/accountClient.js
  src/clients/agreementClient.js
  src/clients/api.js
  src/clients/capital.js
  src/clients/client.js
  src/clients/companyClient.js
  src/clients/marginClient.js
  src/clients/stocks.js
  src/components/AgreementsTable.jsx
  src/components/CompanyDropdown.jsx
  src/components/CurrencyDropdown.jsx
  src/components/FinalizeAgreementModal.jsx
  src/components/FutureDropdown.jsx
  src/components/Header.jsx
  src/components/Payment.jsx
  src/components/StocksDropdown.jsx
  src/components/common/Autocomplete.jsx
  src/components/common/Autocomplete.stories.jsx
  src/components/common/Button.jsx
  src/components/common/Form.jsx
  src/components/common/Modal.jsx
  src/components/common/Select.jsx
  src/components/common/Table.jsx
  src/components/common/TextArea.jsx
  src/components/common/TextField.jsx
  src/components/company/AgreementPointModal.jsx
  src/components/company/CompanyAgreements.jsx
  src/components/company/CompanyBankAccounts.jsx
  src/components/company/CompanyContact.jsx
  src/components/company/CompanyInformation.jsx
  src/components/company/CreateCompanyModal.jsx
  src/components/margins/MarginAddTransactionModal.jsx
  src/components/margins/MarginKapitalBlock.jsx
  src/components/margins/MarginKapitalModal.jsx
  src/components/margins/MarginStateBlock.jsx
  src/components/margins/MarginTransactionModal.jsx
  src/pages/dashboard/agreement-list.jsx
  src/pages/dashboard/agreement-single.jsx
  src/pages/dashboard/capital.jsx
  src/pages/dashboard/company-list.jsx
  src/pages/dashboard/company-single.jsx
  src/pages/dashboard/list.jsx
  src/pages/dashboard/trade.jsx
  src/pages/dashboard/transactionappr.jsx
  src/routes.jsx
Labels: approved, size/XXL

#201 Ispit 1
  cypress/integration/stocks.spec.js
Labels: size/M

#202 UX improvements
  src/components/CashAccountsTable.jsx
  src/components/OtpModal.jsx
  src/components/Payment.jsx
  src/components/UserModal.jsx
  src/components/common/RadioGroup.jsx
  src/components/common/Stats.jsx
  src/components/margins/MarginAddTransactionModal.jsx
  src/components/margins/MarginKapitalBlock.jsx
  src/components/margins/MarginStateBlock.jsx
  src/components/margins/MarginTransactionModal.jsx
  src/pages/dashboard/capital.jsx
  src/pages/dashboard/capitalsecurity.jsx
  src/pages/dashboard/changepass.jsx
  src/pages/dashboard/overview.jsx
  src/pages/dashboard/transactionappr.jsx
Labels: lgtm, approved, size/L

#203 Replace favicon
  public/favicon.ico
Labels: lgtm, approved, size/XS

#204 Treat admin as supervisor
  src/utils.js
Labels: lgtm, approved, size/XS

#206 Mergovanje grane ispit-2 sa masterom
  cypress/integration/stocks.spec.js
  public/favicon.ico
  src/components/CashAccountsTable.jsx
  src/components/OtpModal.jsx
  src/components/Payment.jsx
  src/components/UserModal.jsx
  src/components/common/RadioGroup.jsx
  src/components/common/Stats.jsx
  src/components/margins/MarginAddTransactionModal.jsx
  src/components/margins/MarginKapitalBlock.jsx
  src/components/margins/MarginStateBlock.jsx
  src/components/margins/MarginTransactionModal.jsx
  src/pages/dashboard/capital.jsx
  src/pages/dashboard/capitalsecurity.jsx
  src/pages/dashboard/changepass.jsx
  src/pages/dashboard/overview.jsx
  src/pages/dashboard/transactionappr.jsx
  src/utils.js
Labels: approved

#208 last minute improvements
  src/clients/marginClient.js
  src/components/common/Link.jsx
  src/components/margins/MarginKapitalBlock.jsx
  src/components/margins/MarginKapitalDetails.jsx
  src/components/margins/MarginKapitalModal.jsx
  src/pages/dashboard/agreement-single.jsx
  src/pages/dashboard/capital-margin.jsx
  src/pages/dashboard/capital.jsx
  src/pages/dashboard/capitalsecurity.jsx
  src/pages/dashboard/trade.jsx
  src/routes.jsx
Labels: lgtm, size/L

#209 Ux improvements
  .env.elab
  .env.prod
  .env.test
  package-lock.json
  package.json
  src/components/DashboardPageLayout.jsx
  src/components/DashboardPageLayout.test.js
  src/components/Sidebar.jsx
  src/components/Sidebar.stories.jsx
  src/components/StockTickerWrapper.jsx
  src/components/common/AnimationFadeIn.jsx
  src/components/common/Autocomplete.jsx
  src/components/common/Autocomplete.stories.jsx
  src/components/common/Card.jsx
  src/components/common/ExitButton.jsx
  src/components/common/Modal.jsx
  src/components/common/RadioGroup.jsx
  src/components/common/Select.jsx
  src/components/common/Tab.jsx
  src/components/common/Table.jsx
  src/components/common/TextField.jsx
  src/pages/dashboard/capital.jsx
  src/pages/dashboard/overview.jsx
  src/pages/dashboard/trade.jsx
Labels: size/XXL

#207 I2
  cypress/integration/agreement.spec.js
  cypress/integration/capital.spec.js
  cypress/integration/company.spec.js
Labels: lgtm, approved, size/L

#211 Mergovanje grane ispit-3 sa masterom
  .env.elab
  .env.prod
  .env.test
  cypress/integration/agreement.spec.js
  cypress/integration/capital.spec.js
  cypress/integration/company.spec.js
  package-lock.json
  package.json
  src/clients/marginClient.js
  src/components/DashboardPageLayout.jsx
  src/components/DashboardPageLayout.test.js
  src/components/Sidebar.jsx
  src/components/Sidebar.stories.jsx
  src/components/StockTickerWrapper.jsx
  src/components/common/AnimationFadeIn.jsx
  src/components/common/Autocomplete.jsx
  src/components/common/Autocomplete.stories.jsx
  src/components/common/Card.jsx
  src/components/common/ExitButton.jsx
  src/components/common/Link.jsx
  src/components/common/Modal.jsx
  src/components/common/RadioGroup.jsx
  src/components/common/Select.jsx
  src/components/common/Tab.jsx
  src/components/common/Table.jsx
  src/components/common/TextField.jsx
  src/components/margins/MarginKapitalBlock.jsx
  src/components/margins/MarginKapitalDetails.jsx
  src/components/margins/MarginKapitalModal.jsx
  src/pages/dashboard/agreement-single.jsx
  src/pages/dashboard/capital-margin.jsx
  src/pages/dashboard/capital.jsx
  src/pages/dashboard/capitalsecurity.jsx
  src/pages/dashboard/overview.jsx
  src/pages/dashboard/trade.jsx
  src/routes.jsx
Labels: approved

#212 Mali bag resen
  src/pages/dashboard/transactionappr.jsx
Labels: lgtm, approved, size/XS

#213 Final tests
  cypress.json
  cypress/integration/agreement.spec.js
  cypress/integration/capital.spec.js
  cypress/integration/company.spec.js
  cypress/integration/stocks.spec.js
  cypress/integration/trade.spec.js
  cypress/integration/transactions.spec.js
  cypress/integration/users.spec.js
  cypress/plugins/index.js
  cypress/support/index.js
  src/App.js
  src/components/common/AnimationFadeIn.jsx
  src/components/common/Autocomplete.jsx
  src/components/common/Breadcrumbs.jsx
  src/components/common/Modal.jsx
  src/components/common/Tab.jsx
  src/components/company/CompanyBankAccounts.jsx
  src/components/company/CompanyContact.jsx
  src/components/margins/MarginKapitalBlock.jsx
  src/components/margins/MarginStateBlock.jsx
  src/index.css
  src/pages/dashboard/capital.jsx
Labels: lgtm, size/XL
